repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-added-large-files
  -   id: check-docstring-first
  -   id: check-json
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace


- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
  # Run the linter.
  - id: ruff
    args: [ --fix ]
  # Run the formatter.
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.0  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    args: [--strict, --ignore-missing-imports]
    additional_dependencies: ['types-requests']


- repo: https://github.com/econchick/interrogate
  rev: 1.6.0  # or master if you're bold
  hooks:
  - id: interrogate
    args: [-v, --fail-under=80]
